<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;
use Faker\Factory as Faker;

class PegawaiSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $faker = Faker::create();

        $users = [
            [
                'username' => 'superadmin',
                'password' => bcrypt('superadmin'),
                'email' => 'superadmin@gmail.com',
                'first_name' => 'Super',
                'last_name' => 'Admin',
                'roles_id' => 1,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'admin',
                'password' => bcrypt('admin'),
                'email' => 'admin@gmail.com',
                'first_name' => 'Admin',
                'last_name' => 'Sekolah',
                'roles_id' => 2,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'kepalasekolah',
                'password' => bcrypt('kepalasekolah'),
                'email' => 'kepalasekolah@gmail.com',
                'first_name' => 'Kepala',
                'last_name' => 'Sekolah',
                'roles_id' => 3,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'wakilkepsek',
                'password' => bcrypt('wakilkepsek'),
                'email' => 'wakilkepsek@gmail.com',
                'first_name' => 'Wakil',
                'last_name' => 'Kepala Sekolah',
                'roles_id' => 4,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'guru',
                'password' => bcrypt('guru'),
                'email' => 'guru@gmail.com',
                'first_name' => 'Guru',
                'last_name' => 'Matematika',
                'roles_id' => 5,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'staffadmin',
                'password' => bcrypt('staffadmin'),
                'email' => 'staffadmin@gmail.com',
                'first_name' => 'Staff',
                'last_name' => 'Administrasi',
                'roles_id' => 6,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'kepalaperpustakaan',
                'password' => bcrypt('kepalaperpustakaan'),
                'email' => 'kepalaperpustakaan@gmail.com',
                'first_name' => 'Kepala',
                'last_name' => 'Perpustakaan',
                'roles_id' => 7,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'pustakawan',
                'password' => bcrypt('pustakawan'),
                'email' => 'pustakawan@gmail.com',
                'first_name' => 'Pustakawan',
                'last_name' => 'Sekolah',
                'roles_id' => 8,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'staffkeuangan',
                'password' => bcrypt('staffkeuangan'),
                'email' => 'staffkeuangan@gmail.com',
                'first_name' => 'Staff',
                'last_name' => 'Keuangan',
                'roles_id' => 9,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'koordinator',
                'password' => bcrypt('koordinator'),
                'email' => 'koordinator@gmail.com',
                'first_name' => 'Koordinator',
                'last_name' => 'Kegiatan',
                'roles_id' => 10,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'pengawas',
                'password' => bcrypt('pengawas'),
                'email' => 'pengawas@gmail.com',
                'first_name' => 'Pengawas',
                'last_name' => 'Sekolah',
                'roles_id' => 11,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'siswa',
                'password' => bcrypt('siswa'),
                'email' => 'siswa@gmail.com',
                'first_name' => 'Siswa',
                'last_name' => 'Sekolah',
                'roles_id' => 12,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'orangtua',
                'password' => bcrypt('orangtua'),
                'email' => 'orangtua@gmail.com',
                'first_name' => 'Orangtua',
                'last_name' => 'Siswa',
                'roles_id' => 13,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'alumni',
                'password' => bcrypt('alumni'),
                'email' => 'alumni@gmail.com',
                'first_name' => 'Alumni',
                'last_name' => 'Sekolah',
                'roles_id' => 14,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'vendor',
                'password' => bcrypt('vendor'),
                'email' => 'vendor@gmail.com',
                'first_name' => 'Vendor',
                'last_name' => 'Sekolah',
                'roles_id' => 15,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'ppdb1',
                'password' => bcrypt('ppdb1'),
                'email' => 'ppdb1@gmail.com',
                'first_name' => 'PPDB',
                'last_name' => 'Sekolah1',
                'roles_id' => 16,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'ppdb2',
                'password' => bcrypt('ppdb2'),
                'email' => 'ppdb2@gmail.com',
                'first_name' => 'PPDB',
                'last_name' => 'Sekolah2',
                'roles_id' => 16,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'ppdb3',
                'password' => bcrypt('ppdb3'),
                'email' => 'ppdb3@gmail.com',
                'first_name' => 'PPDB',
                'last_name' => 'Sekolah3',
                'roles_id' => 16,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'ppdb4',
                'password' => bcrypt('ppdb4'),
                'email' => 'ppdb4@gmail.com',
                'first_name' => 'PPDB',
                'last_name' => 'Sekolah4',
                'roles_id' => 16,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'ppdb5',
                'password' => bcrypt('ppdb5'),
                'email' => 'ppdb5@gmail.com',
                'first_name' => 'PPDB',
                'last_name' => 'Sekolah5',
                'roles_id' => 16,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'ppdb6',
                'password' => bcrypt('ppdb6'),
                'email' => 'ppdb6@gmail.com',
                'first_name' => 'PPDB',
                'last_name' => 'Sekolah6',
                'roles_id' => 16,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'ppdb7',
                'password' => bcrypt('ppdb7'),
                'email' => 'ppdb7@gmail.com',
                'first_name' => 'PPDB',
                'last_name' => 'Sekolah7',
                'roles_id' => 16,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'ppdb8',
                'password' => bcrypt('ppdb8'),
                'email' => 'ppdb8@gmail.com',
                'first_name' => 'PPDB',
                'last_name' => 'Sekolah8',
                'roles_id' => 16,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'ppdb9',
                'password' => bcrypt('ppdb9'),
                'email' => 'ppdb9@gmail.com',
                'first_name' => 'PPDB',
                'last_name' => 'Sekolah9',
                'roles_id' => 16,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'ppdb10',
                'password' => bcrypt('ppdb10'),
                'email' => 'ppdb10@gmail.com',
                'first_name' => 'PPDB',
                'last_name' => 'Sekolah10',
                'roles_id' => 16,
                'is_active' => true,
                'is_verified' => true,
            ],
            [
                'username' => 'siswa2',
                'password' => bcrypt('siswa'),
                'email' => 'siswa2@gmail.com',
                'first_name' => 'Siswa2',
                'last_name' => 'Sekolah',
                'roles_id' => 12,
                'is_active' => true,
                'is_verified' => true,
            ]
        ];

        foreach ($users as $user) {
            DB::table('users')->insert([
                'username' => $user['username'],
                'password' => $user['password'],
                'email' => $user['email'],
                'first_name' => $user['first_name'],
                'last_name' => $user['last_name'],
                'roles_id' => $user['roles_id'],
                'is_active' => $user['is_active'],
                'is_verified' => $user['is_verified'],
                'verification_token' => $user['verification_token'] ?? null,
                'reset_token' => $user['reset_token'] ?? null,
                'reset_token_expires_at' => $user['reset_token_expires_at'] ?? null,
                'last_login_at' => $user['last_login_at'] ?? null,
                'last_failed_login_at' => $user['last_failed_login_at'] ?? null,
                'failed_login_count' => $user['failed_login_count'] ?? 0,
                'last_failed_login_ip' => $user['last_failed_login_ip'] ?? null,
                'last_login_ip' => $user['last_login_ip'] ?? null,
                'timezone' => $user['timezone'] ?? null,
                'locale' => $user['locale'] ?? null,
                'ip_address' => $user['ip_address'] ?? null,
            ]);
        }

        $pegawai = [
            [
                'kdprofile' => 1,
                'statusenabled' => 1,
                'namalengkap' => 'Super Admin',
                'nik' => $faker->unique()->numerify('##########'),
                'users_id' => 1,
                'jabatan_id' => 1, // Superadmin
                'jenispegawai_id' => 39,
                'golonganpegawai_id' => 1,
                'unitkerja_id' => 1,
                'kategorypegawai_id' => 1,
                'statuspegawai_id' => 1,
                'kelompokpegawai_id' => 1,
            ],
            [
                'kdprofile' => 1,
                'statusenabled' => 1,
                'namalengkap' => 'Admin Sekolah',
                'nik' => $faker->unique()->numerify('##########'),
                'users_id' => 2,
                'jabatan_id' => 2, // Admin
                'jenispegawai_id' => 2,
                'golonganpegawai_id' => 1,
                'unitkerja_id' => 1,
                'kategorypegawai_id' => 2,
                'statuspegawai_id' => 1,
                'kelompokpegawai_id' => 2,
            ],
            [
                'kdprofile' => 1,
                'statusenabled' => 1,
                'namalengkap' => 'Kepala Sekolah',
                'nik' => $faker->unique()->numerify('##########'),
                'users_id' => 3,
                'jabatan_id' => 3, // Kepala Sekolah
                'jenispegawai_id' => 3,
                'golonganpegawai_id' => 2,
                'unitkerja_id' => 2,
                'kategorypegawai_id' => 1,
                'statuspegawai_id' => 1,
                'kelompokpegawai_id' => 1,
            ],
            [
                'kdprofile' => 1,
                'statusenabled' => 1,
                'namalengkap' => 'Wakil Kepala Sekolah',
                'nik' => $faker->unique()->numerify('##########'),
                'users_id' => 4,
                'jabatan_id' => 4, // Wakil Kepala Sekolah
                'jenispegawai_id' => 4,
                'golonganpegawai_id' => 2,
                'unitkerja_id' => 2,
                'kategorypegawai_id' => 1,
                'statuspegawai_id' => 1,
                'kelompokpegawai_id' => 1,
            ],
            [
                'kdprofile' => 1,
                'statusenabled' => 1,
                'namalengkap' => 'Guru Matematika',
                'nik' => $faker->unique()->numerify('##########'),
                'users_id' => 5,
                'jabatan_id' => 5, // Guru
                'jenispegawai_id' => 5,
                'golonganpegawai_id' => 2,
                'unitkerja_id' => 3,
                'kategorypegawai_id' => 1,
                'statuspegawai_id' => 1,
                'kelompokpegawai_id' => 1,
            ],
            [
                'kdprofile' => 1,
                'statusenabled' => 1,
                'namalengkap' => 'Staff Administrasi',
                'nik' => $faker->unique()->numerify('##########'),
                'users_id' => 6,
                'jabatan_id' => 6, // Staff Administrasi
                'jenispegawai_id' => 6,
                'golonganpegawai_id' => 1,
                'unitkerja_id' => 4,
                'kategorypegawai_id' => 2,
                'statuspegawai_id' => 1,
                'kelompokpegawai_id' => 2,
            ],
            [
                'kdprofile' => 1,
                'statusenabled' => 1,
                'namalengkap' => 'Kepala Perpustakaan',
                'nik' => $faker->unique()->numerify('##########'),
                'users_id' => 7,
                'jabatan_id' => 7, // Kepala Perpustakaan
                'jenispegawai_id' => 7,
                'golonganpegawai_id' => 1,
                'unitkerja_id' => 5,
                'kategorypegawai_id' => 1,
                'statuspegawai_id' => 1,
                'kelompokpegawai_id' => 2,
            ],
            [
                'kdprofile' => 1,
                'statusenabled' => 1,
                'namalengkap' => 'Pustakawan Sekolah',
                'nik' => $faker->unique()->numerify('##########'),
                'users_id' => 8,
                'jabatan_id' => 8, // Pustakawan
                'jenispegawai_id' => 8,
                'golonganpegawai_id' => 1,
                'unitkerja_id' => 5,
                'kategorypegawai_id' => 2,
                'statuspegawai_id' => 1,
                'kelompokpegawai_id' => 2,
            ],
            [
                'kdprofile' => 1,
                'statusenabled' => 1,
                'namalengkap' => 'Staff Keuangan',
                'nik' => $faker->unique()->numerify('##########'),
                'users_id' => 9,
                'jabatan_id' => 9, // Staff Keuangan
                'jenispegawai_id' => 9,
                'golonganpegawai_id' => 1,
                'unitkerja_id' => 6,
                'kategorypegawai_id' => 2,
                'statuspegawai_id' => 1,
                'kelompokpegawai_id' => 2,
            ],
            [
                'kdprofile' => 1,
                'statusenabled' => 1,
                'namalengkap' => 'Koordinator Kegiatan',
                'nik' => $faker->unique()->numerify('##########'),
                'users_id' => 10,
                'jabatan_id' => 10, // Koordinator Kegiatan
                'jenispegawai_id' => 10,
                'golonganpegawai_id' => 1,
                'unitkerja_id' => 7,
                'kategorypegawai_id' => 2,
                'statuspegawai_id' => 1,
                'kelompokpegawai_id' => 2,
            ],
            [
                'kdprofile' => 1,
                'statusenabled' => 1,
                'namalengkap' => 'Pengawas Sekolah',
                'nik' => $faker->unique()->numerify('##########'),
                'users_id' => 11,
                'jabatan_id' => 11, // Pengawas Sekolah
                'jenispegawai_id' => 11,
                'golonganpegawai_id' => 1,
                'unitkerja_id' => 8,
                'kategorypegawai_id' => 1,
                'statuspegawai_id' => 1,
                'kelompokpegawai_id' => 1,
            ],
        ];

        foreach ($pegawai as $item) {
            \App\Models\Master\Pegawai::create($item);
        }
    }
}
