<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use App\Models\Master\Ppdb;

class PpdbSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        $data = [
            [
                'statusenabled' => true,
                'kdprofile' => '1',
                'users_id' => 16,
                'namalengkap' => 'Ahmad Fauzi',
                'namapanggilan' => 'Fauzi',
                'jeniskelamin_id' => 1,
                'tanggallahir' => '2015-03-25',
                'tempatlahir' => 'Jakarta',
                'agama_id' => 1,
                'warganegara_id' => 1,
                'anaknomorke' => 2,
                'jumlahsaudarakandung' => 3,
                'jumlahsaudaratiri' => 0,
                'jumlahsaudaraangkat' => 0,
                'bahasaseharihari' => 'Indonesia',
                'beratbadan' => 20.5,
                'tinggibadan' => 120.0,
                'golongandarah_id' => 1,
                'penyakitpernahdiderita' => 'Cacar air',
                'alamattempattinggal' => 'Jl. Merpati No.10, Jakarta',
                'nomortelepon' => '08123456789',
                'statustempattinggal_id' => 1,
                'namaayah' => 'Budi Santoso',
                'namaibu' => 'Siti Aminah',
                'pendidikan_ayah_id' => 2,
                'pendidikan_ibu_id' => 3,
                'pekerjaan_ayah_id' => 1,
                'pekerjaan_ibu_id' => 2,
                'namawali' => null,
                'pendidikan_wali_id' => null,
                'hubunganwali_id' => null,
                'pekerjaan_wali_id' => null,
                'statusmasuk_id' => 1,
                'namatkasal' => null,
                'tanggalpindahan' => null,
                'kelompokpindahan' => null,
                'tanggalditerima' => '2021-07-15',
                'kelompokditerima' => 'A',
                'statuspendaftaran_id' => 1,
                'alasanpenolakan' => null,
                'nohandphone' => 6285797703142,
            ],
            [
                'statusenabled' => true,
                'kdprofile' => '1',
                'users_id' => 17,
                'namalengkap' => 'Nadia Putri',
                'namapanggilan' => 'Nadia',
                'jeniskelamin_id' => 2,
                'tanggallahir' => '2016-08-15',
                'tempatlahir' => 'Bandung',
                'agama_id' => 2,
                'warganegara_id' => 1,
                'anaknomorke' => 1,
                'jumlahsaudarakandung' => 2,
                'jumlahsaudaratiri' => 0,
                'jumlahsaudaraangkat' => 0,
                'bahasaseharihari' => 'Sunda',
                'beratbadan' => 18.0,
                'tinggibadan' => 115.0,
                'golongandarah_id' => 2,
                'penyakitpernahdiderita' => null,
                'alamattempattinggal' => 'Jl. Kencana No.25, Bandung',
                'nomortelepon' => '08223456789',
                'statustempattinggal_id' => 1,
                'namaayah' => 'Rudi Hartono',
                'namaibu' => 'Maya Sari',
                'pendidikan_ayah_id' => 4,
                'pendidikan_ibu_id' => 3,
                'pekerjaan_ayah_id' => 3,
                'pekerjaan_ibu_id' => 4,
                'namawali' => null,
                'pendidikan_wali_id' => null,
                'hubunganwali_id' => null,
                'pekerjaan_wali_id' => null,
                'statusmasuk_id' => 1,
                'namatkasal' => null,
                'tanggalpindahan' => null,
                'kelompokpindahan' => null,
                'tanggalditerima' => '2021-07-20',
                'kelompokditerima' => 'B',
                'statuspendaftaran_id' => 1,
                'alasanpenolakan' => null,
                'nohandphone' => 6285797703142,
            ],
            [
                'statusenabled' => true,
                'kdprofile' => '1',
                'users_id' => 18,
                'namalengkap' => 'Rian Nugraha',
                'namapanggilan' => 'Rian',
                'jeniskelamin_id' => 1,
                'tanggallahir' => '2015-12-30',
                'tempatlahir' => 'Surabaya',
                'agama_id' => 3,
                'warganegara_id' => 1,
                'anaknomorke' => 3,
                'jumlahsaudarakandung' => 2,
                'jumlahsaudaratiri' => 1,
                'jumlahsaudaraangkat' => 0,
                'bahasaseharihari' => 'Jawa',
                'beratbadan' => 19.0,
                'tinggibadan' => 118.0,
                'golongandarah_id' => 1,
                'penyakitpernahdiderita' => 'Asma',
                'alamattempattinggal' => 'Jl. Kenanga No.45, Surabaya',
                'nomortelepon' => '08323456789',
                'statustempattinggal_id' => 2,
                'namaayah' => 'Andi Saputra',
                'namaibu' => 'Indah Lestari',
                'pendidikan_ayah_id' => 2,
                'pendidikan_ibu_id' => 4,
                'pekerjaan_ayah_id' => 2,
                'pekerjaan_ibu_id' => 1,
                'namawali' => 'Eka Prasetya',
                'pendidikan_wali_id' => 3,
                'hubunganwali_id' => 2,
                'pekerjaan_wali_id' => 3,
                'statusmasuk_id' => 2,
                'namatkasal' => 'TK Melati',
                'tanggalpindahan' => '2021-05-10',
                'kelompokpindahan' => 'B',
                'tanggalditerima' => '2021-06-01',
                'kelompokditerima' => 'B',
                'statuspendaftaran_id' => 2,
                'alasanpenolakan' => 'Tidak sesuai usia',
                'nohandphone' => 6285797703142,
            ]
        ];

        foreach ($data as $item) {
            Ppdb::create($item);
        }
    }
}
